nama_lengkap = ("Muhammad Fatih")
panggilan = ("Fatih")
nim = ('0110222013')
pekerjaan = ("Mahasiswa")
tinggi_badan = ('166')
berat_badan = ('149')
alamat = ("Jl. Sholeh iskandar RT02/RW13")
agama = ("Islam")
berat_badan_edal = ('58.5-60')

a=float (berat_badan)/2

print()
print("1) 8 Variabel")
print()
print("Nama Lengkap :",nama_lengkap)
print("Panggilan    :",panggilan)
print("NIM          :",nim)
print("Pekerjaan    :",pekerjaan)
print("Tinggi Badan :",tinggi_badan)
print("Berat Badan  :",a)
print("Agama        :",agama)
print("Alamat       :",alamat)
print()
print("2) Buktikan tipe data bolean dari data diri")
print()
print("apakah berat badan saya ideal?",berat_badan_edal==berat_badan)
print()